### ISSUE TITLE
Memory Errors

### ISSUE THREAD

**Issue by feesta** [migurski/Dymo#1]
I'm getting some memory errors. Zooms 4 and 5 worked without a problem:

python ../dymo-label.py -z 6 --max-temp 1000 --min-temp 0.00001 --steps 100000 ./NA-labels-z6.json ./NA-points-z6.json ../data/North-America-z6.txt.gz
 Temperature        Energy    Accept   Improve     Elapsed   Remaining
     1000.00      10070.00                         0:00:00
      541.10       8803.33    97.54%    42.89%     0:01:24     0:40:35
      292.85       8278.09    95.05%    42.90%     0:03:03     0:42:38
      158.46       8755.08    92.14%    41.90%     0:05:00     0:45:03
       85.76       7170.35    86.53%    39.09%     0:08:05     0:52:33
       46.41       5788.57    75.61%    34.83%     0:12:27     1:02:13
       25.11       5681.68    66.83%    29.30%     0:17:07     1:08:26
       13.59       4835.58    53.80%    23.79%     0:23:03     1:15:43
        7.36       4443.27    40.35%    16.62%     0:30:26     1:23:42
Traceback (most recent call last):
  File "../dymo-label.py", line 77, in <module>
    places, e = annealer.anneal(places, options.temp_max, options.temp_min, options.steps, 30)
  File "./dymo/Dymo/anneal.py", line 153, in anneal
    bestState = copy.deepcopy(state)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 279, in _deepcopy_inst
    return x.__deepcopy__(memo)
  File "./dymo/Dymo/places.py", line 227, in **deepcopy**
    _neighbors = deepcopy(self._neighbors, memo_dict),
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 255, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.6/copy.py", line 192, in deepcopy
    _keep_alive(x, memo) # Make sure x lives at least as long as d
  File "/usr/lib/python2.6/copy.py", line 272, in _keep_alive
    memo[id(memo)].append(x)
MemoryError
make: **\* [z6] Error 1

python ../dymo-label.py -z 6 --max-temp 700 --min-temp 0.00001 --steps 100000 ./NA-labels-z6.json ./NA-points-z6.json ../data/North-America-z6.txt.gz
 Temperature        Energy    Accept   Improve     Elapsed   Remaining
      700.00      10070.00                         0:00:00
      383.30       8468.56    96.64%    43.34%     0:01:22     0:39:49
      209.93       8567.73    92.92%    41.10%     0:03:01     0:42:14
      114.95       7102.21    88.87%    40.76%     0:05:07     0:46:07
       62.96       6573.38    80.05%    37.56%     0:08:29     0:55:08
       34.48       5746.46    68.89%    31.83%     0:12:42     1:03:32
       18.88       5399.15    59.00%    25.67%     0:17:50     1:11:19
       10.34       4611.85    48.60%    20.58%     0:24:54     1:21:49
Traceback (most recent call last):
  File "../dymo-label.py", line 77, in <module>
    places, e = annealer.anneal(places, options.temp_max, options.temp_min, options.steps, 30)
  File "./dymo/Dymo/anneal.py", line 143, in anneal
    state = copy.deepcopy(prevState)
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 279, in _deepcopy_inst
    return x.__deepcopy__(memo)
  File "./dymo/Dymo/places.py", line 226, in **deepcopy**
    _places = deepcopy(self._places, memo_dict),
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 228, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.6/copy.py", line 162, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.6/copy.py", line 279, in _deepcopy_inst
    return x.__deepcopy__(memo)
  File "./dymo/Dymo/places.py", line 83, in **deepcopy**
    self.position, self.radius, self.rank, *_extras)
  File "./dymo/Dymo/places.py", line 24, in **init**
    self.fontsize = fontsize
MemoryError
make: *_\* [z6] Error 1

**Comment by migurski** [comment]
Fixed for you in 35bb532.

**Comment by feesta** [comment]
Wow so much better!
